[[constraint]]
  name = "github.com/openshift/origin"
  version = "<3.7.0"

[[constraint]]
  name = "k8s.io/kubernetes"
  source = "https://github.com/openshift/kubernetes.git"

[[constraint]]
  name = "k8s.io/apiserver"
  source = "https://github.com/openshift/kubernetes-apiserver.git"

[[constraint]]
  name = "k8s.io/kube-aggregator"
  source = "https://github.com/openshift/kubernetes-kube-aggregator.git"

[[constraint]]
  name = "k8s.io/apimachinery"
  source = "https://github.com/openshift/kubernetes-apimachinery.git"

[[constraint]]
  name = "k8s.io/client-go"
  source = "https://github.com/openshift/kubernetes-apiserver.git"

[[constraint]]
  name = "github.com/emicklei/go-restful-swagger12"
  source = "https://github.com/openshift/emicklei-go-restful-swagger12.git"

[[constraint]]
  name = "github.com/google/cadvisor"
  source = "https://github.com/openshift/google-cadvisor.git"

[[constraint]]
  name = "github.com/cloudflare/cfssl"
  source = "https://github.com/openshift/cloudflare-cfssl.git"

[[constraint]]
  name = "github.com/skynetservices/skydns"
  source = "https://github.com/openshift/skynetservices-skydns.git"

[[constraint]]
  name = "github.com/google/certificate-transparency"
  source = "https://github.com/openshift/google-certificate-transparency.git"

[[constraint]]
  name = "github.com/opencontainers/runc"
  source = "https://github.com/openshift/opencontainers-runc.git"

[[constraint]]
  name = "golang.org/x/crypto"
  source = "https://github.com/golang/crypto.git"
